### ISSUE TITLE
Add --open flag to open browser window

### ISSUE THREAD

**Issue by cw789** [kettle11/devserver#20]
This is not an issue. Just a very tiny little suggestion.
But not that important anymore as URLs are anyway most time clickable in terminals now.

In case of implementation one should take default HTTPS or HTTP.

Implementation detail:

```
# Windows
cmd c/ start url

# Darwin
open url

# Linux
xdg-open url
```

**Comment by cw789** [comment]
Close as it's not an issue.

**Comment by kettle11** [comment]
Hi @cw789! Sorry I didn't respond to this and you're other comments! I've been very busy and haven't found enough time for `devserver`. 

I'd certainly accept a pull request for this if someone felt it was worthwhile and it were a small change. But as you said it's not a huge deal because generally it's possible to click URLs in the terminals.

**Comment by cw789** [comment]
No need to say sorry. Thank you for the great tool. It's really the best (for WebXR). I've tested them all. I would have started one for myself if yours won't have existed.

Of course I'll come back with a pull request if time and a real need will be given.

It's always better to focus on important things - so this one was closed.
